// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp7YJbcF4KcnkF9JsYvKHQFX0uqVyvkJ8',
    appId: '1:741255835225:web:0ccd66060c0a6f9d750b48',
    messagingSenderId: '741255835225',
    projectId: 'myapp-65c52',
    authDomain: 'myapp-65c52.firebaseapp.com',
    storageBucket: 'myapp-65c52.appspot.com',
    measurementId: 'G-JQ1DPQHMQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEpe6G7KGZZirQgpce7jD_5twjiXR7txo',
    appId: '1:741255835225:android:9fd97d6d77a4affb750b48',
    messagingSenderId: '741255835225',
    projectId: 'myapp-65c52',
    storageBucket: 'myapp-65c52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnsbRXbgQgPPaBVkQ5OzdCTnwsZgMvgo',
    appId: '1:741255835225:ios:c92caa55908a31b8750b48',
    messagingSenderId: '741255835225',
    projectId: 'myapp-65c52',
    storageBucket: 'myapp-65c52.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKnsbRXbgQgPPaBVkQ5OzdCTnwsZgMvgo',
    appId: '1:741255835225:ios:c92caa55908a31b8750b48',
    messagingSenderId: '741255835225',
    projectId: 'myapp-65c52',
    storageBucket: 'myapp-65c52.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp7YJbcF4KcnkF9JsYvKHQFX0uqVyvkJ8',
    appId: '1:741255835225:web:7f94682aab151e24750b48',
    messagingSenderId: '741255835225',
    projectId: 'myapp-65c52',
    authDomain: 'myapp-65c52.firebaseapp.com',
    storageBucket: 'myapp-65c52.appspot.com',
    measurementId: 'G-3NBQC8B4CY',
  );
}
